"""DSL parser for .loop and .vertex files."""

from .ast import (
    Boundary,
    BoundaryAfter,
    BoundaryEvery,
    BoundaryWhen,
    Coerce,
    Duration,
    FoldAvg,
    FoldBy,
    FoldCollect,
    FoldCount,
    FoldDecl,
    FoldLatest,
    FoldMax,
    FoldMin,
    FoldOp,
    FoldSum,
    FoldWindow,
    LoopDef,
    LoopFile,
    LStrip,
    ParseStep,
    Pick,
    Replace,
    RStrip,
    Skip,
    Split,
    Strip,
    Transform,
    TransformOp,
    Trigger,
    VertexFile,
)
from .errors import DSLError, LexError, Location, ParseError, ValidationError
from .lexer import Token, TokenType, tokenize
from .parser import parse_loop, parse_loop_file, parse_vertex, parse_vertex_file
from .validator import validate, validate_loop, validate_vertex
from .mapper import (
    CircularVertexError,
    CompiledVertex,
    compile_loop,
    compile_vertex,
    compile_vertex_recursive,
    materialize_vertex,
)

__all__ = [
    # AST types - Loop file
    "LoopFile",
    "Duration",
    "ParseStep",
    "Skip",
    "Split",
    "Pick",
    "Transform",
    "TransformOp",
    "Strip",
    "LStrip",
    "RStrip",
    "Replace",
    "Coerce",
    "Trigger",
    # AST types - Vertex file
    "VertexFile",
    "LoopDef",
    "FoldDecl",
    "FoldOp",
    "FoldAvg",
    "FoldBy",
    "FoldCollect",
    "FoldCount",
    "FoldLatest",
    "FoldMax",
    "FoldMin",
    "FoldSum",
    "FoldWindow",
    "Boundary",
    "BoundaryAfter",
    "BoundaryEvery",
    "BoundaryWhen",
    # Lexer
    "Token",
    "TokenType",
    "tokenize",
    # Parser
    "parse_loop",
    "parse_loop_file",
    "parse_vertex",
    "parse_vertex_file",
    # Errors
    "DSLError",
    "LexError",
    "ParseError",
    "ValidationError",
    "Location",
    # Validator
    "validate",
    "validate_loop",
    "validate_vertex",
    # Mapper
    "compile_loop",
    "compile_vertex",
    "compile_vertex_recursive",
    "materialize_vertex",
    "CompiledVertex",
    "CircularVertexError",
]
