"""sdk — Loops apex composition library.

The single headless composition layer over engine, custody, lang, store, atoms, and sign.
Provides high-level, transport-agnostic read, emit, and kind mutation operations
returning typed result models.
"""

from .declare import (
    DeclarationEditResult,
    DeclarationPreviewResult,
    edit_declaration,
    init_vertex,
    inspect_declaration,
    recover_declaration,
)
from .emit import CustodyCredentialProvider, emit_batch, emit_fact, preview_emission
from .errors import (
    ArrivalRefusal,
    CommittedIncomplete,
    CommittedOutcome,
    CommittedOutcomeUnknown,
    CommittedProjectionFailed,
    CommittedUnwitnessed,
    ProjectionOutcomeUnknown,
    normalize_exception,
)
from .kind import (
    add_kind,
    edit_kind,
    grant_observer,
    plan_kind_mutation,
    recover_ceremony,
    remove_kind,
    revoke_observer,
)
from .read import (
    read_fact_by_id,
    read_facts,
    read_state,
    read_summary,
    read_ticks,
    read_timeline,
    resolve_entity,
    search_facts,
    sync_search_index,
    sync_target,
)
from .sources import run_sources
from .target import TargetInfo, discover_targets, resolve_arrival_target, resolve_target
from .transfer import (
    ExportPublicationError,
    ExportResult,
    RestoreForwardResult,
    export_target,
    restore_forward,
)
from .types import (
    AdmissionFailed,
    ArrivalTarget,
    BatchEmitResult,
    CeremonyFailed,
    CommittedEmissionError,
    DeclarationInspectionResult,
    DeclarationPlanResult,
    EmissionFailed,
    EmitPreviewResult,
    EmitReceipt,
    EntityResolutionResult,
    FactLookupResult,
    FactPageResult,
    FoldStateResult,
    InitVertexResult,
    InvalidEmissionRequest,
    KindMutationResult,
    LegacyBatchPartialFailure,
    ReadSummary,
    SdkError,
    SdkValueError,
    SearchIndexResult,
    SearchResult,
    SearchResultItem,
    SourceCadenceResult,
    SourceCollectedResult,
    SourceDispatchResult,
    SourceFactResult,
    SourceRunResult,
    SourceTerminalResult,
    SourceTierResult,
    StoreDescriptorInfo,
    SyncResult,
    TargetError,
    TargetNotFound,
    TargetNotWritable,
    TargetUnsupported,
    TickReadResult,
    TimelineEvent,
    TimelineResult,
    VerifyResult,
)
from .verify import verify_target

__all__ = [
    # Operations
    "resolve_target",
    "export_target",
    "restore_forward",
    "resolve_arrival_target",
    "discover_targets",
    "init_vertex",
    "inspect_declaration",
    "edit_declaration",
    "recover_declaration",
    "read_summary",
    "read_facts",
    "read_state",
    "read_ticks",
    "read_fact_by_id",
    "search_facts",
    "sync_search_index",
    "resolve_entity",
    "read_timeline",
    "sync_target",
    "verify_target",
    "emit_fact",
    "emit_batch",
    "preview_emission",
    "run_sources",
    "add_kind",
    "edit_kind",
    "remove_kind",
    "grant_observer",
    "revoke_observer",
    "plan_kind_mutation",
    "recover_ceremony",
    # Providers
    "CustodyCredentialProvider",
    # Models
    "TargetInfo",
    "ExportResult",
    "RestoreForwardResult",
    "ArrivalTarget",
    "StoreDescriptorInfo",
    "InitVertexResult",
    "DeclarationInspectionResult",
    "DeclarationEditResult",
    "DeclarationPreviewResult",
    "DeclarationPlanResult",
    "ReadSummary",
    "FactPageResult",
    "FactLookupResult",
    "FoldStateResult",
    "TickReadResult",
    "EmitReceipt",
    "BatchEmitResult",
    "EntityResolutionResult",
    "EmitPreviewResult",
    "SearchResult",
    "SearchResultItem",
    "SearchIndexResult",
    "SourceFactResult",
    "SourceCadenceResult",
    "SourceCollectedResult",
    "SourceDispatchResult",
    "SourceTierResult",
    "SourceTerminalResult",
    "SourceRunResult",
    "TimelineResult",
    "TimelineEvent",
    "SyncResult",
    "VerifyResult",
    "KindMutationResult",
    # Exceptions
    "SdkError",
    "ExportPublicationError",
    "SdkValueError",
    "TargetError",
    "TargetNotFound",
    "TargetUnsupported",
    "TargetNotWritable",
    "AdmissionFailed",
    "EmissionFailed",
    "InvalidEmissionRequest",
    "LegacyBatchPartialFailure",
    "CommittedEmissionError",
    "CeremonyFailed",
    "ArrivalRefusal",
    "CommittedOutcome",
    "CommittedIncomplete",
    "CommittedOutcomeUnknown",
    "CommittedProjectionFailed",
    "CommittedUnwitnessed",
    "ProjectionOutcomeUnknown",
    "normalize_exception",
]
